build_from:
  aarch64: ghcr.io/yeraze/meshmonitor:3.3.0
  amd64: ghcr.io/yeraze/meshmonitor:3.3.0
  armhf: ghcr.io/yeraze/meshmonitor:3.3.0
  armv7: ghcr.io/yeraze/meshmonitor:3.3.0
  i386: ghcr.io/yeraze/meshmonitor:3.3.0
