build_from:
  aarch64: ghcr.io/yeraze/meshmonitor:3.6.3
  amd64: ghcr.io/yeraze/meshmonitor:3.6.3
  armhf: ghcr.io/yeraze/meshmonitor:3.6.3
  armv7: ghcr.io/yeraze/meshmonitor:3.6.3
  i386: ghcr.io/yeraze/meshmonitor:3.6.3
