build_from:
  aarch64: ghcr.io/yeraze/meshmonitor:3.2.4
  amd64: ghcr.io/yeraze/meshmonitor:3.2.4
  armhf: ghcr.io/yeraze/meshmonitor:3.2.4
  armv7: ghcr.io/yeraze/meshmonitor:3.2.4
  i386: ghcr.io/yeraze/meshmonitor:3.2.4
