build_from:
  aarch64: ghcr.io/yeraze/meshmonitor:3.4.1
  amd64: ghcr.io/yeraze/meshmonitor:3.4.1
  armhf: ghcr.io/yeraze/meshmonitor:3.4.1
  armv7: ghcr.io/yeraze/meshmonitor:3.4.1
  i386: ghcr.io/yeraze/meshmonitor:3.4.1
